## Due date: Tuesday 01/21 at 11.59 pm ##

# Lab 1: Linear Algebra with Numpy and Simpy#

Welcome to lab in Math 182! In this first lab you will get acquainted with the computing environment of the course and you will start to use Python and some of its libraries. You will learn:

- Some basic use of python
- How to generate vectors and matrix in Python with numpy 
- How to do basic operations with vectors and matrix in Python with numpy
- How to find eigenvectors and eigenvalues in Python with the module linalg of numpy
- Singular value decomposition in Python with the module linalg
- How to find the reduced echelon form of a matrix using simpy
- How to find the null space of a matrix using simpy
- How to diagonalize a matrix using simpy
- `Table` methods from the `datascience` library:
    - Creation: `with_column` and `with_columns`
    - Accessing and using values as inputs to a function: `apply`


## Part 1: Expression and Function ##
Python can be used to compute simple numerical expression as:

In [2]:
(2+3)/4+2**3

9.25

For a table of common operators look at https://www.inferentialthinking.com/chapters/03/1/Expressions.html.
You can use assignment statement like the following to create named variables.

In [3]:
a = 10
b = 20
a + b

30

You can also create string variable.

In [4]:
c="Hello"
d="Welcome to Math 180A"
c+", "+d

'Hello, Welcome to Math 180A'

Some basic function as abs or round are built into the Python language and they are available by default. The name of the function appears first, followed by expressions in parentheses.

In [5]:
abs(-3)


3

In [6]:
round(2.5)

2

Most functions that are built into the Python language are stored in a collection of functions called a library. An import statement is used to provide access to a library, such as math or operator. 

In [7]:
import math
import operator
math.sqrt(operator.add(4, 5))


3.0

In [8]:
math.log(16, 2)

4.0

Note that anytime you call a function that belongs to a particular module (math), you need to import the library and to call it before the name of the function, followed by dot as math.log.

If you need a particular function and you don't know the name or how to use it, look for it on the internet!!! You will find manual reference and examples!

In Python, you can also create your own function, using the statement 'def'. In the following, we create a function that square a number and add 1.

In [9]:
def ourfunction(x):
    return x**2+1

We can call ourfunction in exactly the same way we have called other functions.

In [10]:
ourfunction(2)

5

To acquire a little bit of practice in the creation of function you can look at https://www.inferentialthinking.com/chapters/08/Functions_and_Tables.html

## Part 2: Matrices and vectors with numpy ##
You can use numpy to create matrices and vectors.

In [11]:
import numpy as np

In [12]:
M=np.array(([1,2,3],
            [1,4,6],
            [7,8,9]))
v=np.array(([1],
            [2],
            [3]))

In [13]:
M

array([[1, 2, 3],
       [1, 4, 6],
       [7, 8, 9]])

In [14]:
v

array([[1],
       [2],
       [3]])

You can use name_of_array.shape to visualise the dimension of the array.

In [15]:
M.shape

(3, 3)

In [16]:
v.shape

(3, 1)

Numpy provides also many convenience functions for creating matrices and vectors. For example:

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.full((3,3),4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [21]:
np.random.random((3,3))

array([[0.41518829, 0.43491237, 0.29415844],
       [0.12662893, 0.96429477, 0.22082866],
       [0.68939961, 0.71134816, 0.14302594]])

You can also create a matrix from different vectors using the function vstack or hstack.

In [22]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])
v3=np.array([7,8,9])
np.vstack([v1,v2,v3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.hstack([v1,v2,v3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

You can access a particular element of a matrices of an array indicating in [,] the numbers of the indices. Remember that python starts to enumerate from zero!

In [24]:
M

array([[1, 2, 3],
       [1, 4, 6],
       [7, 8, 9]])

In [25]:
M[1,1]

4

In [26]:
M[np.array((0,2)),:]

array([[1, 2, 3],
       [7, 8, 9]])

## Part 3: Basic operations with vectors and matrices ##
You can use numpy to do basic operations with vectors and matrices.
You can find the transpose of a matrix with the function name_of_matrix.T

In [27]:
M.T

array([[1, 1, 7],
       [2, 4, 8],
       [3, 6, 9]])

You can use np.dot(array1,array2) to do the dot product between array1 and array2.
Note that if array1 is a matrix and array2 is a vector, this is equivalent to do the usual matrix-vector multiplication.
If array1 and array2 are matrices, this is equivalent to do the usual matrix-matrix multiplication.

Be careful with the dimensions of the two arrays. As you know, the second dimension of array1 needs to be the same as the first dimension of array2!!!

In [28]:
np.dot(M,v)

array([[14],
       [27],
       [50]])

In [29]:
np.dot(M,M)

array([[ 24,  34,  42],
       [ 47,  66,  81],
       [ 78, 118, 150]])

In [30]:
np.dot(v.T,v)

array([[14]])

This is equivalent to $$\mid\mid v \mid\mid^2$$

You can use np.multiply(array1,array2) to do elementwise multiplications.

In [31]:
np.multiply(M,v)

array([[ 1,  2,  3],
       [ 2,  8, 12],
       [21, 24, 27]])

Remember that this is the same of using the multiplication symbol in Python. 

In [32]:
M*v

array([[ 1,  2,  3],
       [ 2,  8, 12],
       [21, 24, 27]])

You can also use the plus and the minus symbol to perform addition and subtraction between arrays.

In [33]:
M+v

array([[ 2,  3,  4],
       [ 3,  6,  8],
       [10, 11, 12]])

In [34]:
M-v

array([[ 0,  1,  2],
       [-1,  2,  4],
       [ 4,  5,  6]])

You can also use Python to find the the inverse of a matrix, if it exists. For this you need the module linalg.

In [35]:
 np.linalg.inv(M)  

array([[ 2.        , -1.        ,  0.        ],
       [-5.5       ,  2.        ,  0.5       ],
       [ 3.33333333, -1.        , -0.33333333]])

## Part 4: Eigenvectors and Eigenvalues ##
You can use Python to find eigenvectors and eigenvalues of a matrix.

In [36]:
eigvals, eigvecs = np.linalg.eig(M)

In [37]:
eigvals   #eigenvalues (each is repeated according to its multiplicity)

array([15.40300337,  0.23745467, -1.64045804])

In [38]:
eigvecs #eigenvectors (each columns is an eigenvectors)

array([[-0.24202867, -0.36814314, -0.26105397],
       [-0.46834426,  0.81408602, -0.68124275],
       [-0.84975042, -0.44914873,  0.68392919]])

The ith column of eigevecs is a eigenvectors corresponding to the ith element of eigvals. Verify in the following that this is true for the first eigenvalue.

In [44]:
#student: print M*first_eigenvectors
first_eigenvectors = np.array([[eigvecs[0][0]],
                               [eigvecs[1][0]],
                               [eigvecs[2][0]]])
print (np.dot(M,first_eigenvectors))


[[ -3.72796845]
 [ -7.21390823]
 [-13.08870857]]


In [45]:
#student: print first_eigenvalue*first_eigenvector
print (eigvals[0]*first_eigenvectors)


[[ -3.72796845]
 [ -7.21390823]
 [-13.08870857]]


The eigenvectors returned by the function eig are the normalized ones. Check this using the function norm of the module linalg.

In [46]:
#student
np.linalg.norm(first_eigenvectors)

0.9999999999999999

In [47]:
#student
second_eigenvectors = np.array([[eigvecs[0][1]],
                                [eigvecs[1][1]],
                                [eigvecs[2][1]]])
np.linalg.norm(second_eigenvectors)

0.9999999999999999

In [48]:
#student
third_eigenvectors = np.array([[eigvecs[0][2]],
                               [eigvecs[1][2]],
                               [eigvecs[2][2]]])
np.linalg.norm(third_eigenvectors)

1.0

## Part 5: Singular Value Decomposition ##
We can also use the module linalg to find the singular value decomposition of a matrix with the function svd.
$$
M=USV^\top
$$
where U and V are two orhtogonal matrix and S is a diagonal matrix with on the diagonal the singular values of the matrix.

In [49]:
U, s, Vtranspose = np.linalg.svd(M) 

In [50]:
U #(orthogonal matrix)

array([[-0.23059422, -0.26001128, -0.93766755],
       [-0.43454031, -0.83469387,  0.33832066],
       [-0.87063254,  0.48546914,  0.07949019]])

In [51]:
Vtranspose #(orthogonal matrix)

array([[-0.42441679, -0.57541144, -0.69912235],
       [ 0.85139306,  0.00922329, -0.52444712],
       [-0.30822109,  0.81781208, -0.48598679]])

In [52]:
s #(singular values: diagonal of S)

array([15.92670794,  2.70565844,  0.13923623])

In the following verify that $M=USV^\top$ asking Python to compute $USV^\top$.

In [53]:
#student
S=np.diag(s)
np.dot(np.dot(U,S),Vtranspose)

array([[1., 2., 3.],
       [1., 4., 6.],
       [7., 8., 9.]])

You know that the singular values of the matrix M are the non negative square roots of the eignevalues of $$M^\top M.$$ In the following, verify that:

In [54]:
#student (print the eignevalues of M^TM)
eigvals, eigvecs = np.linalg.eig(np.dot(M.T,M))
eigvals

array([2.53660026e+02, 7.32058760e+00, 1.93867284e-02])

In [55]:
#student (print the square of the singular values of M)
s[0] = s[0]**2
s[1] = s[1]**2
s[2] = s[2]**2
print (s)


[2.53660026e+02 7.32058760e+00 1.93867284e-02]


The rows of $V^\top$ are the eignevectors of $M^\top M$.
The columns of $U$ are the eigenvectors of $M M^\top$.
Verify that this is true.

In [56]:
#student (print the eigenvectors of M^T*M)
eigvecs

array([[ 0.42441679,  0.85139306,  0.30822109],
       [ 0.57541144,  0.00922329, -0.81781208],
       [ 0.69912235, -0.52444712,  0.48598679]])

In [57]:
#student (print the eigenvectors of M*M^T)
eigvals, eigvecs = np.linalg.eig(np.dot(M,M.T))
eigvecs

array([[-0.23059422, -0.93766755, -0.26001128],
       [-0.43454031,  0.33832066, -0.83469387],
       [-0.87063254,  0.07949019,  0.48546914]])

## Part 6: Reduced Echelon form and Null space with Simpy ##
The library Simpy can be used to find the reduced echelon form of a matrix without having to deal with the long process of doing it by hand.
Let's first of all import the library.

In [64]:
from sympy import *

To apply on a matrix the function offered by this library we need to express the matrix as a simpy object rather then a numpy array. To do so, we use the function Matrix.

In [65]:
M = Matrix([[3, -2,  4, -2], [5,  3, -3, -2], [5, -2,  2, -2], [5, -2, -3,  3]])
M

Matrix([
[3, -2,  4, -2],
[5,  3, -3, -2],
[5, -2,  2, -2],
[5, -2, -3,  3]])

We can find the reduced echelon form of the matrix, using the function name_of_matrix.rref().

In [66]:
M.rref()

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0],
 [0, 0, 0, 1]]), (0, 1, 2, 3))

The first element is the matrix in reduced echelon form and the second is a list of indices of pivot columns.

Given the matrix in reduced echelon form, what is the rank of the matrix? What is the nullity?

#student
rank(M)=...
nullity(M)=...

What is the nullspace of M?

#student
The nullspace of N is...

You can verify your answer using name_of_matrix.nullspace()

In [67]:
M.nullspace()

[]

## Part 7: Diagonalization with Simpy ##
The library Simpy can also be used to diagonalize a matrix. This can be done with name_of_matrix.diagonalize().

In [68]:
P, D = M.diagonalize()
P

Matrix([
[0, 1, 1,  0],
[1, 1, 1, -1],
[1, 1, 1,  0],
[1, 1, 0,  1]])

In [69]:
D

Matrix([
[-2, 0, 0, 0],
[ 0, 3, 0, 0],
[ 0, 0, 5, 0],
[ 0, 0, 0, 5]])

In the following verify that $M=PDP^{-1}$. Note: In Simpy you can use the usual * to perform multiplications between matrices.

In [70]:
#student
P*D*(P**-1)

Matrix([
[3, -2,  4, -2],
[5,  3, -3, -2],
[5, -2,  2, -2],
[5, -2, -3,  3]])

Verify that the elements that form the diagonal of D are eigenvalues of the matrix M and that the columns of the matrix P are eigenvectors of the matrix M.
You can find help using the following documentation:
https://docs.sympy.org/0.7.5/tutorial/matrices.html

In [71]:
#student
M.eigenvals()

{3: 1, -2: 1, 5: 2}

In [73]:
M.eigenvects()

[(-2, 1, [Matrix([
   [0],
   [1],
   [1],
   [1]])]), (3, 1, [Matrix([
   [1],
   [1],
   [1],
   [1]])]), (5, 2, [Matrix([
   [1],
   [1],
   [1],
   [0]]), Matrix([
   [ 0],
   [-1],
   [ 0],
   [ 1]])])]

In [178]:
P

Matrix([
[0, 1, 1,  0],
[1, 1, 1, -1],
[1, 1, 1,  0],
[1, 1, 0,  1]])

Are the columns of P orthonormal? Yes or No? Use python to support your answer.

In [75]:
#student
#No
np.dot(P.col(0).T,P.col(1))[0][0]
#non-zero, thus not orthogonal

3

## Part 8: Table ##
Tables are a fundamental object type to work in Probability and Data Science. To work with table, we will make use of the library datascience. We import all of the module called datascience.

In [76]:
from datascience import *

Let's assume to have an urn with 3 red balls, 4 blue balls and 5 black balls.
If we pick at random a ball from the urn we have:
$$P(red)=3/12=1/4$$ $$P(blue)=4/12=1/3$$  $$P(black)=5/12$$.
We create now a table with the outcomes of this experiment and with their probability.

Empty tables can be created using the Table function:

In [77]:
Table()

The with_columns can be used to add columns. 
Each column need to be an array.
In the following we create a table named Urn with two columns, one with the outcomes, and one with the probabilities.

In [78]:
Urn=Table().with_columns(
    'Outcome', make_array('red', 'blue', 'black'),
    'P(Outcome)', make_array(1/4, 1/3, 5/12),
    
)


In [79]:
Urn

Outcome | P(Outcome)
red     | 0.25
blue    | 0.333333
black   | 0.416667

You can study the size of the table in the following way:

In [80]:
Urn.num_columns

2

In [81]:
Urn.num_rows

3

Let's now add a column with the probability of the complement of the event.
First Create a function that, given the probability of an event, return the probability of the complement.
(We know that $$P(A^c)=1-P(A)$$)

In [82]:
#student
def complement(p):
    return (1-p)

We can apply function to columns with the command apply.

In [83]:
Urn=Urn.with_columns(
    'P(Outcome^C)', Urn.apply(complement, 'P(Outcome)')
)
Urn

Outcome | P(Outcome) | P(Outcome^C)
red     | 0.25       | 0.75
blue    | 0.333333   | 0.666667
black   | 0.416667   | 0.583333

You can select only some column using its/their names like in the following:

In [84]:
Urn.column('Outcome')

array(['red', 'blue', 'black'], dtype='<U5')

You can also drop a column from a table.

In [85]:
Urn.drop('Outcome')

P(Outcome) | P(Outcome^C)
0.25       | 0.75
0.333333   | 0.666667
0.416667   | 0.583333

For a complete reference of the functionalities of datascience library look at http://data8.org/datascience/index.html.

## Part 7:Use of if/else statement ##
We illustrate here how to use the if/else statement in Python. As before, let's assume to have a urn with 5 red balls and 3 blue ones and let's assume to pick a ball at random. We want to create a distribution table like in the previous section. Let's start with a column of possible outcomes. Create a table with one column with the possible outcomes.

In [86]:
#student
Urn3=Table().with_columns(
    'Outcome', make_array('red', 'blue'),
)

Urn3

Outcome
red
blue

We create now a function, that given the outcome, return the probability.

In [87]:
def p(x):
    if x=='blue':
        return 3/8
    else:
        return 5/8
    
p('red')

0.625

Add now a column of probabilities to the table using the function p and print out the table.

In [88]:
#student
Urn3=Urn3.with_columns(
    'P(Outcome)', Urn3.apply(p, 'Outcome')
)
Urn3

Outcome | P(Outcome)
red     | 0.625
blue    | 0.375

## Submission Instructions ##

Many assignments throughout the course will have a written portion and a code portion. Please follow the directions below to properly submit both portions.

### Written Portion ###
*  Scan all the pages into a PDF. You can use any scanner or a phone using applications such as CamScanner. Please **DO NOT** simply take pictures using your phone. 
* **Please start a new page for each PART**. If you have already written multiple questions on the same page, you can crop the image in CamScanner or fold your page over (the old-fashioned way). This helps expedite grading.
* It is your responsibility to check that all the work on all the scanned pages is legible.

### Code Portion ###
* Save your notebook using File > Save and Checkpoint.
* Use File > Downland as > PDF via Latex.
* Download the PDF file and confirm that none of your work is missing or cut off. 
### Submitting ###
* Combine the PDFs from the written and code portions into one PDF.  [Here](https://smallpdf.com/merge-pdf) is a useful tool for doing so.  
* Submit the assignment to Lab1 on Gradescope. 
* **Make sure to assign each page of your pdf to the correct question.**

